### ISSUE TITLE
Unable to subscribe podcast

### ISSUE THREAD

**Issue by aleung** [cnpolitics/radio#1]
1. 网页 http://cnpolitics.github.io/radio 上的RSS链接无效

2. 从网上找到可用的RSS地址 http://cnpolitics.github.io/radio/pub/feed.xml ，里面音频下载指向服务器地址 http://radio-static.cnpolitics.org/ ，例如 http://radio-static.cnpolitics.org/mig/audio/ep6.mp3 ，下载会出错。

> ERROR
> 
> The requested URL could not be retrieved
> 
> While trying to retrieve the URL: http://radio-static.cnpolitics.org/mig/audio/ep6.mp3
> 
> The following error was encountered:
> 
> Read Error
> The system returned:
> 
>     (104) Connection reset by peer
> An error condition occurred while reading data from the network. Please retry your request.
> 
> Your cache administrator is support@quantil.com. 
> Generated Thu, 30 Nov 2017 04:16:57 GMT by cache.51cdn.com (Cdn Cache Server V2.0)

**Comment by realfish** [comment]
感谢反馈，请问你所在的地区以及网络服务商是什么？

播客网站 [cnpolitics.github.io/radio](https://cnpolitics.github.io/radio) 尚有诸多不完善，界面上的链接信息也可能有误，非常抱歉。播客订阅方式请参考：<https://github.com/cnpolitics/radio/wiki/subscription-guide>

- - -

关于 `radio-static.cnpolitics.org` 域名，目前该域名作为播客的静态资源服务器，使用了「[七牛云](https://www.qiniu.com/)」服务。之前也出现过部分地区（尤其是中国大陆以外地区），访问该服务器的静态资源出错的问题。曾与七牛云客服做过反馈，但似乎没有明显改善。我们也正在考虑将播客音频的托管迁移到更为稳定的服务上。

**Comment by realfish** [comment]
另外，最新的播客频道「针尖」在网易云音乐平台上有同步更新，可以作为一个替代渠道备选：<http://music.163.com/#/djradio?id=333322059>

**Comment by aleung** [comment]
我目前在大陆，在直连状态连接 http://cnpolitics.github.io 不稳定，但若通过VPN连接又变成到 http://radio-static.cnpolitics.org 的连接不稳定。

**Comment by realfish** [comment]
为提升播客音频资源访问的稳定性，「针尖」频道的音频资源，去年末起已迁移至 Amazon S3 服务，并启用新域名 `radio-static.zjian.org` 作为音频资源服务器的地址（ 64b3912 ）。若有问题，可另起 issue 反馈。

再次感谢此前的反馈。

**Comment by tonywangcn** [comment]
@aleung 修复了这个问题。https://tonywangcn.github.io/radio/feed.xml
